name: Build Monitoring IaC

on:
  push:
    paths:
      - '5 - monitoring/**'
  pull_request:
    paths:
      - '5 - monitoring/**'
  workflow_dispatch:

env:
  allFiles: ${{ github.event_name != 'pull_request' || ( github.base_ref == 'main') }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  build:
    name:  Build Integration monitoring IaC
    runs-on: ubuntu-latest
    environment: monitoring
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - uses: maikvandergaag/action-biceplint@main
        id: lint
        with:
          allfiles: ${{ env.allFiles }}
          create-sarif: false
          markdown-report: false
      - uses: actions/upload-artifact@v4
        name: Upload IaC artifacts
        with:
          name: iac
          path: |
            ${{ github.workspace }}/bicepconfig.json
            ${{ github.workspace }}/5 - monitoring/**/*.bicep
            ${{ github.workspace }}/5 - monitoring/**/*.bicepparam